//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	static class Game
	{
		public static List<Monster> monsters = new List<Monster>();
		public static Object mapPrefab = Resources.Load ("Prefabs/Map");
		public static PlayerController player;
		public static string mapPath = "Maps/Map1.xml";
		public static MapUtil map;


		public static void addMonster(float x, float y, float z, int scariness) 
		{
			Object monsterToAdd = Monster.create(x, y, z, scariness);
		}

		public static void removeMonster(int index) 
		{
			monsters [index].kill ();
			monsters.RemoveAt (index);
		}

		public static Monster getMonster(int index) 
		{
			return monsters[index];
		}

		public static void init(PlayerController gamePlayer) {
			// Initiate the map
			int mapSize = 100;
			map = new MapUtil (mapSize, mapSize);

			int halfWidth = map.getHalfWidth();
			int halfHeight = map.getHalfHeight();

			player = gamePlayer;

			int numMonsters = mapSize * mapSize / 400;
			Debug.Log (numMonsters);
			for (int i = 0; i < numMonsters; i ++) {
				addMonster (Random.Range (-halfWidth, halfWidth), 3, Random.Range (-halfHeight, halfHeight), (int)((float)i / (float)numMonsters * 50));
			}
		}
	}
}

