//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class PathSegment
	{
		PathSegment previous;
		Cell current;

		public PathSegment (Cell current, PathSegment previous)
		{
			this.previous = previous;
			this.current = current;
		}

		public PathSegment (Cell current) {
			this.previous = null;
			this.current = current;
		}



		public PathSegment getPrevious() {
			return previous;
		}

		public Cell getCurrent() {
			return current;
		}
	}
}

